appName: nginxapp
port: 80
namespace: default

spec:
  replicas: 5

configmap:
  name: nginx-configmap-v1

image:
  name: nginx
  tag: latest

container:
  containerName: nginx-container

requests:
  memory: "16Mi" 
  cpu: "50m"

limits:
  memory: "128Mi" 
  cpu: "100m"