apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      tier: nginx
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        tier: nginx
    spec: # Pod Specifications
      containers:
      - name: {{ .Values.container.containerName }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
        resources:
          requests:
            memory: {{ .Values.requests.memory }} 
            cpu: {{ .Values.requests.cpu }}
          limits:
            memory: {{ .Values.limits.memory }} 
            cpu: {{ .Values.limits.cpu }}
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-content
        configMap:
          name: {{ .Values.configmap.name }}