name: Deploy to QA

on:
  push:
    branches:
      - qa
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'qa'

jobs:
  deploy:
    uses: templates/deployment-template.yaml@feature/deploy-to-minikube-cluster
    with:
      environment: qa
      values_file: values-qa.yaml
