name: Deploy to Kubernetes

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - prd

jobs:
  build_and_deploy:
    runs-on: 
      - self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: jamilusman/webserver

    - name: Set Execution Policy
      shell: powershell
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process

    - name: Install Docker
      shell: powershell
      run: |
        $ErrorActionPreference = 'Stop'
        # Download Docker Engine installer
        Invoke-WebRequest -Uri "https://download.docker.com/win/static/stable/x86_64/docker-20.10.7.zip" -OutFile "$env:TEMP\docker.zip"
        # Extract Docker Engine
        Expand-Archive -Path "$env:TEMP\docker.zip" -DestinationPath "$env:ProgramFiles\Docker"
        # Add Docker to PATH
        [System.Environment]::SetEnvironmentVariable('PATH', "$env:ProgramFiles\Docker", [System.EnvironmentVariableTarget]::Machine)
        # Verify Docker installation
        docker --version
        docker run hello-world

    - name: Install Minikube
      shell: powershell
      run: |
        # Download Minikube binary
        Invoke-WebRequest -Uri "https://storage.googleapis.com/minikube/releases/latest/minikube-windows-amd64.exe" -OutFile "$env:USERPROFILE\minikube.exe"
        # Move Minikube to PATH
        Move-Item -Path "$env:USERPROFILE\minikube.exe" -Destination "$env:ProgramFiles\Minikube\minikube.exe"
        # Add Minikube to PATH
        [System.Environment]::SetEnvironmentVariable('PATH', "$env:ProgramFiles\Minikube", [System.EnvironmentVariableTarget]::Machine)
        # Verify Minikube installation
        minikube version

    - name: Set up Minikube
      shell: powershell
      run: |
        minikube start --driver=docker
        kubectl config use-context minikube
        # Verify Minikube is running
        kubectl cluster-info
        kubectl get nodes

    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Build image
      run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t jamilusman/nginx:latest .
          echo -n "verifying images:"
          docker images

    - name: Deploy to Kubernetes
      run: |

        helm upgrade webapp-release-qa webapp/ --values webapp/values.yaml -f webapp/values-qa.yaml -n qa

        # Use Helm to deploy with the appropriate values file
        # helm upgrade --install my-release ./charts \
        #   --namespace ${{ github.event.inputs.environment }} \
        #   --values values-${{ github.event.inputs.environment }}.yaml

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f templates/configmap.yaml
        kubectl apply -f templates/deployment.yaml
        kubectl apply -f templates/service.yaml

    # - name: Verify deployment
    #   run: |
    #     kubectl rollout status deployment/nginx-deployment
    #     kubectl get pods