name: Deploy to Kubernetes

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - prd

jobs:
  build_and_deploy:
    runs-on: 
      - self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: jamilusman/webserver

    - name: Set Execution Policy
      shell: powershell
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process

    - name: Install Docker
      shell: powershell
      run: |
        docker --version

    - name: Check Minikube Version
      shell: powershell
      run: |
        minikube version

    - name: Set up Minikube
      shell: powershell
      run: |
        Start-Process powershell -Verb runAs -ArgumentList "minikube start --driver=docker"

    - name: Try the cluster !
      run: kubectl get pods -A
      
    - name: Build image
      shell: powershell
      run: |
        cd webapp
        docker build -f ./Dockerfile -t nginx:latest .

    - name: Deploy to Kubernetes
      run: |

        helm upgrade webapp-release-qa webapp/ --values webapp/values.yaml -f webapp/values-qa.yaml -n qa

        # Use Helm to deploy with the appropriate values file
        # helm upgrade --install my-release ./charts \
        #   --namespace ${{ github.event.inputs.environment }} \
        #   --values values-${{ github.event.inputs.environment }}.yaml

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f templates/configmap.yaml
        kubectl apply -f templates/deployment.yaml
        kubectl apply -f templates/service.yaml

    # - name: Verify deployment
    #   run: |
    #     kubectl rollout status deployment/nginx-deployment
    #     kubectl get pods