name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deployment-template.yaml
    with:
      environment: prd
      values_file: values-prd.yaml